<script>
    import Nav from "../navbar.svelte"
    import { Heading, P, A, Button } from 'flowbite-svelte';
    import { Alert, Spinner } from 'flowbite-svelte';
    import { InfoCircleSolid } from 'flowbite-svelte-icons';
    import Footer from "../footer.svelte"
    let currentIndex = 0;
    import gallery1 from '$lib/images/gallery1-min.png';
    import gallery2 from '$lib/images/gallery2-min.png';
    import gallery3 from '$lib/images/gallery3-min.png';
    import gallery4 from '$lib/images/gallery4-min.png';
    const images = [
      gallery1,
      gallery2,
      gallery3,
      gallery4
    ];
  let downloading = false; // This controls the visibility of the element

  function toggleVisibility() {
    downloading = !downloading; // Toggle the boolean value on button click
  }
  import { onDestroy } from 'svelte';
  
  const changeSlide = () => {
    currentIndex = (currentIndex + 1) % images.length;
  };

  const interval = setInterval(changeSlide, 4000);
  onDestroy(() => {
    clearInterval(interval);
  });
</script>
<style>
    .transition-transform {
      transition: transform 0.5s ease-in-out;
    }
</style>
<Nav />

<div class="flex space-x-4">
    <div class="w-50">
        <Heading tag="h1" class="mb-4" customSize="text-4xl font-extrabold  md:text-5xl lg:text-6xl">Gilbert Server World Download</Heading>
        <p class="text-lightParagraph dark:text-paragraph p-0 mb-10">Load a backup of the minecraft server in single player.</p>
        <Button on:click={toggleVisibility} size='lg' class='btn bg-pink-500' href="https://www.dropbox.com/scl/fi/o03cjxcnf3qyw957d4kow/GilbertServerWorld.zip?rlkey=gjnhhof7n42d8tomdsn7cth6r&e=1&st=cwpm4ms4&dl=1">
          {#if downloading}
            <Spinner class="me-3" size="4" color="white" />
          {/if}
          Download the World</Button>
    </div>
    <div class="relative w-full max-w-4xl mx-auto" style="margin-left: auto">
        <!-- Container for the images -->
        <div class="overflow-hidden rounded-2xl">
          <div
            class="relative flex transition-transform duration-1000 ease-in-out"
            style="transform: translateX(-{currentIndex * 100}%)"
          >
            {#each images as image}
              <img  src={image} alt="Slideshow" class="w-full h-auto object-cover" loading="lazy"/>
            {/each}
    
          </div>
        </div>  
    </div>  
</div>
<hr class="my-12 h-0.5 border-t-0 bg-neutral-200 dark:bg-white/10" />
<h2 class="heading-primary mt-10"> How to install the world</h2>
<Alert border color="red" class="mx-20">
    <InfoCircleSolid slot="icon" class="w-5 h-15" />
    <p>Warning! The custom terrian in the world are generated by the server and new vanilla chunks will be generated in single player. See <a href="/mods" class="font-semibold underline hover:text-red-800 dark:hover:text-red-900">installing mods</a> to load the world with the correct mods.</p>
</Alert>
<h2 class="heading-secondary">Download the world</h2>
<p class="text-lightParagraph dark:text-paragraph">Download the zip file on this webpage. The file is large so it may take a while</p>
<br>
<h2 class="heading-secondary">Transfer it into your saves folder</h2>
<p class="text-lightParagraph dark:text-paragraph">Open your minecraft saves folder. You can find this folder by opening file explorer and typing <b>%appdata%\.minecraft\saves</b> into the top bar. Once you open this folder, drag the zip file that you downloaded into the saves folder.</p>
<div class="flex items-center justify-center p-10"> 
  <enhanced:img src="/static/file-tutorial-1.png?enhanced" sizes="min(1280px, 100vw)" alt="file explorer" class="object-center"/>
</div>

<br>
<h2 class="heading-secondary">Extract the file</h2>
<p class="text-lightParagraph dark:text-paragraph">Right click the zip file and select <b>Extract all</b>. No need to change the extract path, it will extract all the files into the correct folder by default.</p>
<div class="flex p-10">
  <enhanced:img src="/static/file-tutorial-2.png?enhanced" alt="extract all button" class="mr-20"/>
  <enhanced:img src="/static/file-tutorial-3.png?enhanced" alt="extracted file"/>
</div>
<p class="text-lightParagraph dark:text-paragraph">Once you finish extracting the world file, you can delete the original zip file.</p>
<br>
<h2 class="heading-secondary">Play</h2>
<p class="text-lightParagraph dark:text-paragraph">The world file is now inside your local singleplayer saves! To join the world, you must launch <b>Minecraft 1.21.1</b>. You can join the world without mods, however, new chunks that are generated will be different as there is no custom terrain generation.</p>
<enhanced:img src="/static/file-tutorial-4.png?enhanced" sizes="min(1280px, 100vw)" alt="play the world in singleplayer" class="w-full p-10"/>
<Footer />